version: '2.3'
networks:
  mussi:
    driver: bridge
services:
  web:
    build:
      context: .
      args:
        RUN_ENVIRONMENT: docker
    restart: on-failure
    cpus: "0.4"
    mem_reservation: "120m"
    environment:
      FLASK_DEBUG: 1
    networks:
      - mussi
    ports:
      - "8000:5000"
    volumes:
      - ${PWD}:/app/zen
    command: ["wait-for-it", "db:5432", "--"]
  graphql:
    build:
      context: .
      args:
        RUN_ENVIRONMENT: docker
    networks:
      - mussi
    ports:
      - "8883:8888"
    volumes:
      - ${PWD}:/app/zen
    entrypoint: ["/bin/sh", "/app/zen/graphql_entrypoint.sh"]
